name: GetStats
on:
  push:
  workflow_dispatch:

jobs:
  build_matrix:
    name: Build clan matrix
    runs-on: ubuntu-latest
    outputs:
      clan_matrix: ${{ toJSON(steps.get_cmd.outputs.clan_matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Get JSON
        id: get_json
        env:
          GET_CMD: ${{ secrets.BASE_CMD }}
        run: |
          echo ::set-output name=json_var::$(curl "$GET_CMD")

      - name: Get actions
        id: get_cmd
        env:
          json_var: ${{ steps.get_json.outputs.json_var }}
        run: |
          echo ::set-output name=clan_cmd::${{fromJSON(env.json_var).clan_cmd}}
          echo ::set-output name=clan_url::${{fromJSON(env.json_var).clan_url}}
          echo ::set-output name=clan_list::${{fromJSON(env.json_var).clans[0]}}
          echo ::set-output name=clan_matrix::${{fromJSON(toJSON(fromJSON(env.json_var).players))}}
          

      - name: Check command
        id: check_cmd
        env:
          clan_cmd: ${{ steps.get_cmd.outputs.clan_cmd }}
          clan_url: ${{ steps.get_cmd.outputs.clan_url }}
          clan_list: ${{ steps.get_cmd.outputs.clan_list }}
          clan_matrix: ${{ steps.get_cmd.outputs.clan_matrix }}
        run: |
          echo ::set-output name=clan_url::${{format(env.clan_url, env.clan_list)}}
          echo ::set-output name=clan_cmd::${{env.clan_cmd}}
          echo ${{ env.clan_matrix }}
          # echo toJSON(env.clan_matrix.players)
    
      - name: Create command
        id: create_cmd
        env: 
          clan_url: ${{ steps.check_cmd.outputs.clan_url }}
          clan_cmd: ${{ steps.check_cmd.outputs.clan_cmd }}
        run: |
          echo ::set-output name=cmd_to_run::${{format(env.clan_cmd, env.clan_url)}}
          
      - name: Run command
        id: run_cmd
        env:
          cmd_to_run: ${{ steps.create_cmd.outputs.cmd_to_run }}
        run: |
          echo $(${{env.cmd_to_run}} >> clan.json)

      - name: Display file
        id: disp_file
        run: |
          echo $(tail -10 clan.json)
        
  run_matrix:
    runs-on: ubuntu-latest
    needs:
      - build_matrix
    strategy:
      matrix:
        clans: ${{ fromJSON(needs.build_matrix.outputs.clan_matrix) }}
        
    steps:
      - name: Matrix => (${{ matrix.clans }}
        run: |
          echo ${{ matrix.clans }}

    
