name: GetStats
on:
  push:
  workflow_dispatch:

jobs:
  build_cmd:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get JSON
        env:
          GET_CMD: ${{ secrets.BASE_CMD }}
        id: get_json
        run: |
          echo ::set-output name=json_var::$(curl "$GET_CMD")
      - name: Get command
        id: get_cmd
        run: |
          echo ::set-output name=clan_cmd::${{fromJson(steps.get_json.outputs.json_var).clan_cmd}}
          echo ::set-output name=clan_url::${{fromJson(steps.get_json.outputs.json_var).clan_url}}
          echo ::set-output name=clan_list::${{fromJson(steps.get_json.outputs.json_var).clans[0]}}
        env:
          json_var: ${{ steps.get_json.outputs.json_var }}
      - name: Check command
        id: check_cmd
        run: |
          echo ${{ steps.get_cmd.outputs.clan_cmd }}
          echo ${{ steps.get_cmd.outputs.clan_url }}
          echo ${{ steps.get_cmd.outputs.clan_list }}
          echo format('{{ steps.get_cmd.outputs.clan_url }} ', 'Mona')
        env:
          cl_cmd: ${{ steps.get_cmd.outputs.clan_cmd }}
          cl_url: ${{ steps.get_cmd.outputs.clan_url }}
          cl_clan_list: ${{ steps.get_cmd.outputs.clan_list }}
        
