name: GetChaos
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Test curl
      - name: Getting stuff
        env:
          CONF: secret.CONF_URL
          BASE: ${{ secrets.TS_BASE }}
          GET_CLAN: ${{ secrets.GET_CLAN }}
          CHAOS: ${{ secrets.CHAOS }}
          SUTEKH: ${{ secrets.SUTEKH }}
        run: |
          curl "$GET_CLAN$CHAOS"| jq . > chaos.json
      - uses: actions/upload-artifact@v2
        with:
          name: chaos
          path: chaos.json
