name: GetStats
on:
  push:
  workflow_dispatch:

jobs:
  build_cmd:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get JSON
        id: get_json
        env:
          GET_CMD: ${{ secrets.BASE_CMD }}
        run: |
          echo ::set-output name=json_var::$(curl "$GET_CMD")

      - name: Get actions
        id: get_cmd
        env:
          json_var: ${{ steps.get_json.outputs.json_var }}
        run: |
          echo ::set-output name=clan_cmd::${{fromJson(steps.get_json.outputs.json_var).clan_cmd}}
          echo ::set-output name=clan_url::${{fromJson(steps.get_json.outputs.json_var).clan_url}}
          echo ::set-output name=clan_list::${{fromJson(steps.get_json.outputs.json_var).clans[0]}}

      - name: Check command
        id: check_cmd
        env:
          cl_cmd: ${{ steps.get_cmd.outputs.clan_cmd }}
          cl_url: ${{ steps.get_cmd.outputs.clan_url }}
          cl_clan_list: ${{ steps.get_cmd.outputs.clan_list }}
        run: |
          echo ${{ steps.get_cmd.outputs.clan_cmd }}
          echo ${{ steps.get_cmd.outputs.clan_url }}
          echo ${{ steps.get_cmd.outputs.clan_list }}
          echo ::set-output name=clan_url::${{format(steps.get_cmd.outputs.clan_url, steps.get_cmd.outputs.clan_list)}}
          echo ::set-output name=clan_cmd::${{steps.get_cmd.outputs.clan_cmd}}
    
      - name: Create command
        id: create_cmd
        env: 
          clan_url: ${{ steps.check_cmd.outputs.clan_url }}
          clan_cmd: ${{ steps.check_cmd.outputs.clan_cmd }}
        run: |
          echo ${{ env.clan_url }}
          echo ${{ env.clan_cmd }}
          echo ::set-output name=cmd_to_run::${{format(env.clan_cmd, env.clan_url)}}
          
      - name: Run command
        id: run_cmd
        env:
          cmd_to_run: ${{ steps.create_cmd.outputs.cmd_to_run }}
        run: |
          echo ${{ env.cmd_to_run }}
          echo ${{ steps.create_cmd.outputs.cmd_to_run }}
        
        
