name: GetChaos
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting stuff
        env:
          CONF: secret.CONF_URL
          BASE: ${{ secrets.TS_BASE }}
          GET_CLAN: ${{ secrets.GET_CLAN }}
          CHAOS: ${{ secrets.CHAOS }}
          SUTEKH: ${{ secrets.SUTEKH }}
        run: |
          # curl "$GET_CLAN$CHAOS"| jq . > chaos.json
          GET_CURRENT=$(cat << EOF
          $FETCH
          EOF
          )
          echo "::set-output name=content::$GET_CURRENT"
        id: get_current
        
      - name: Get it done
        run: |
          echo "The string is: ${{ steps.get_current.outputs.content }}"
        # env:
          # GET_CURRENT: ${{ format({{ $FETCH }}, {{ $GET_CLAN }}, {{ $CHAOS }}) }}
        # run: |
         # echo $GET_CURRENT
          # echo GET_CURRENT format($FETCH,$GET_CLAN,$CHAOS)
          # echo $GET_CURRENT
      #- name: test
      #  uses: frabert/replace-string-action@v2.0
      #  with:
      #    pattern: 'Hello, (\w+)!'
      #    string: 'Hello, world!'
      #    replace-with: 'I greet you, $1!'
      #- name: test showoff
      #  run: |
      #    echo $replaced
          
# - uses: actions/upload-artifact@v2
      #  with:
       #   name: chaos
        #  path: chaos.json
