name: GetChaos
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting stuff
        env:
          CONF: secret.CONF_URL
          BASE: ${{ secrets.TS_BASE }}
          GET_CLAN: ${{ secrets.GET_CLAN }}
          CHAOS: ${{ secrets.CHAOS }}
          SUTEKH: ${{ secrets.SUTEKH }}
        run: |
          # curl "$GET_CLAN$CHAOS"| jq . > chaos.json
      - name: Get it done
        env:
          GET_CURRENT: format($FETCH, $GET_CLAN, $CHAOS)
        run: |
          echo $GET_CURRENT
      - uses: actions/upload-artifact@v2
        with:
          name: chaos
          path: chaos.json
