name: GetStats
on:
  push:
  workflow_dispatch:

jobs:
  build_cmd:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get JSON
        env:
          GET_CMD: ${{ secrets.BASE_CMD }}
        id: get_json
        run: |
          echo ::set-output name=json_var::$(curl "$GET_CMD" | jq '.')
      - name: Get command
        id: get_cmd
        run: |
          echo $json_var
        env:
          json_var: ${{ steps.get_json.outputs.json_var}}
